apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: pra
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
        - name: flask
          image: docker.io/pra/flask-sqlite:2.0
          imagePullPolicy: Never
          env:
            - name: DB_PATH
              value: /data/app.db
            - name: BACKUP_DIR
              value: /backup
          ports:
            - containerPort: 8080
          command: ["/bin/sh","-lc"]
          args:
            - |
              cd /opt/app && gunicorn -w 2 -b 0.0.0.0:8080 app:app
          volumeMounts:
            - name: data
              mountPath: /data
            - name: backup        # ✅ AJOUTÉ
              mountPath: /backup  # ✅ AJOUTÉ
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: pra-data
        - name: backup            # ✅ AJOUTÉ
          persistentVolumeClaim:  # ✅ AJOUTÉ
            claimName: pra-backup # ✅ AJOUTÉ